#!/bin/bash
#
# A bash script to build the standalone executables for morse_trainer.  Uses 
# 'pyinstaller' to generate an executable for the architecture  it is run on.
# Executable files are:
#     morse_trainer_Linux
#     morse_trainer_Darwin
#     morse_trainer_Windows

# make the pyinstaller executable directory
rm -Rf dist build
pyinstaller -F --noconsole morse_trainer.py

# now rename and move the executable directory
cd dist
mv morse_trainer ../morse_trainer_$(uname)
cd ..
rm -Rf dist build __pycache__ *.spec
